std = "roblox"

exclude = [
    "Packages",
    "_Index",
    "build",
    "release"
]

[lints]

unused_variable = "warn"
shadowing = "warn"
multiple_statements = "allow"
mixed_table = "allow"
undefined_variable = "warn"

[config]
empty_if = "allow"
empty_loop = "allow"

[rules]
global_usage = "allow"
